name: "godot-ci export"
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents:
    write


env:
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: Nickel2Danmaku
  PROJECT_PATH: .

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: debug
        run: |
          ls ./build/linux/
      - name: package
        uses: vimtor/action-zip@v1
        with:
          files: |
            ./build/linux/Nickel2Danmaku.x86_64
            ./build/linux/Nickel2Danmaku.pck
          dest: ./build/linux/linux.zip
      - name: release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          prerelease: true
          files: ./build/linux/linux.zip
